name: README Thumbnail GitHub CI/CD test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
    - name: Run script
      run: python readme_thumbnails.py
    - name: Test with unittest
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python tests/test_readme_thumbnails.py

